name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e

          echo "📁 Navigate to project directory"
          cd ~/Flasks-Devops-Project

          echo "⬇️ Pull latest code"
          git pull origin main

          echo "🐳 Stop old container"
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true

          echo "🏗️ Build new image"
          sudo docker build -t flask-cicd-project .

          echo "🚀 Run container"
          sudo docker run -d -p 5000:5000 --name flask-app flask-cicd-project

          echo "✅ Deployment successful!"